### ISSUE TITLE
[Windows] Cannot launch the game

### ISSUE THREAD

**Issue by macmmm81** [ItsSim/fsolauncher#14]
I can't run the game because the launcher does not detect the components as installed (No green check marks in the Installer tab)

Yes, I have read FAQ and yes, I have tried whitelisting and disabling my antivirus. Unfortunately, despite trying multiple times I wasn't able to properly install all components and as such - launch the game. Are there any logs I can give you to resolve this issue?

**Comment by ItsSim** [comment]
Yes, I’m planning a workaround for this. There’s no certain way to fix this for everyone, since for some it’ll be the antivirus, for others it’ll be some other kind of sandboxing or protection going on preventing the launcher from accessing the Windows registry. While for the majority this does not happen, it’s still a big issue.

Future versions will handle the installation taking into account if registry access is allowed. 

In the meantime, as the FAQ for this problem suggests, running the FreeSO.exe executable from the installation folder will allow you to play the game.

**Comment by ItsSim** [comment]
The workaround right now is to rely on the default installation paths for each component, which the launcher already supports.
The launcher is able to find each component when installed in their default directory. When the file chooser pops up for you to choose a directory don’t do anything - just click the Install button for every popup.

![image](https://user-images.githubusercontent.com/35347872/133774012-495396ae-d3a6-4cc7-9d7e-06bb9a62c99a.png)
