### ISSUE TITLE
[Windows] Cant play the sims online 

### ISSUE THREAD

**Issue by Troublezz** [ItsSim/fsolauncher#9]
Ive download the freeso open beta to play the sims but this keeps popping up and i dont know what to do
![15880368310254752843937414461516](https://user-images.githubusercontent.com/64448261/80436358-f5fe2180-88cc-11ea-92c2-e3573de90339.jpg)

**Comment by ItsSim** [comment]
Hello,
Please try reinstalling The Sims Online by following these steps:

![image](https://user-images.githubusercontent.com/35347872/80437250-6b83e500-8901-11ea-8567-2f6f307bf3e1.png)

Try choosing a different installation directory this time. For example, leave it default instead of choosing My Documents.

**Comment by Troublezz** [comment]
What do you mean i dont understand is there a certain way and place im supposed to place the documents?

**Comment by Troublezz** [comment]
Or what your saying is when i save it dont save it under my documents

**Comment by ItsSim** [comment]
Yes, do not save it under Documents

**Comment by Troublezz** [comment]
Ok i uninstalled the whole the and starting over ima see if that works

**Comment by ItsSim** [comment]
Closed after 24h of inactivity.
